### ISSUE TITLE
Remove need for daemon

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#31]
Because, it sucks.

**Comment by mefellows** [comment]
cc: @zbintliff would appreciate your thoughts.

**Comment by zbintliff** [comment]
Just a few questions:
>Continue to have a separate 'installation step', but instead of having a daemon that wraps the Ruby binaries, we just install the pact-standalone binaries onto the global PATH
Is this what other libs do?

All for using brew to distribute them.

>Do nothing, and wait for Pact Reference to be completed and go straight to that.
Is there a timeline there?

**Comment by mefellows** [comment]
No, other libs pull in the package dynamically at install time e.g. npm will install the binaries into the `node_modules/...` directory tree. 

No timeline for the reference to be implemented (is ASAP an answer?), although there is a lot of activity in this space.

**Comment by bmarini** [comment]
I definitely prefer making less assumptions about how the ruby deps are installed and just relying on PATH.

**Comment by mefellows** [comment]
OK so a working daemonless setup can be found in the `feat/daemonless` branch: https://github.com/pact-foundation/pact-go/tree/feat/daemonless

**TODO**:

- [ ] Working tests and examples
- [ ] Ensure setup/installation notes are clear and easy to follow
- [ ] Working Windows/Appveyor build
- [ ] Healthcheck feature to ensure library compatible with CLI (as they will now be installed separately)
- [ ] Update release page, docs and publish new binary to notify of "deprecation"
