### ISSUE TITLE
Feature: Support Asynchronous Messages

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-go#74]
Add support for asynchronous communication, including but not limited to the following types of integrations:

* Publish/Subscribe via message queues (e.g. Kinesis, SNS, MQ)
* WebSockets where messages may originate from client or server and _in any order_
* AWS Lambda or other "serverless"-like environments

**TODO**:

- [x] Spike out producer and consumer side
- [x] Release latest Ruby standalone (1.33.0+ with message-pact and latest verifier)
- [x] Re-introduce UTF-8 related examples when https://github.com/pact-foundation/pact-node/issues/75 is fixed
- [x] Merge with daemonless and new matching changes into `[release/1.x.x](https://github.com/pact-foundation/pact-go/tree/release/1.x.x)` branch
- [x] Create example project
- [x] Release as beta in parallel with master
- [x] Update documentation
- [x] Handle provider states during verification
- [x] Ensure https://github.com/pact-foundation/pact-go/issues/70 is fixed and released
- [x] Ensure sufficient test coverage
- [x] Review all `TODO`s in the code
- [x] Merge and ensure compatibility with PR #78 
- [x] Migrate to dep #77 
- [x] Merge #79 
- [x] Move CI to Travis and use tag-based deployment. Remove / Fix Wercker.

**Comment by mefellows** [comment]
Just merged in ed918c7b144b2fb49f11f99c9e793fd1adc970dc 🚀.
